name: deploy-allure-report  📊 📝 📁 📄 🕒 📈 📊️ ➡️ 🔄 📋 📞

on: [ push ]

jobs:
  tests:
    name: Test Execution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v4
    - name: Setting up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies    
      run: npm ci && npx playwright install

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history